### ISSUE TITLE
Sensor saknas

### ISSUE THREAD

**Issue by HAPSagan** [popeen/Home-Assistant-Custom-Component-Hemglass#9]
Jag har två olika instanser av HomeAssistant, en hemma och en i vårt fritidshus.

När jag lägger till integrationen i vårt fritidshus (Latitude, 63,34 och Longitude 13,44) skapas två sensorer, en sensor.hemglass och en sensor.hemglass_truck. 

sensor.hemglass har ett tillstånd och följande attribut:
Attribut
Latitude
Longitude
StreetAddress
City
Time
ETA
Salesman
Depot
Email
Comment
Canceled
CanceledMessage
TruckIsActiveToday
TruckLocationUpdated
TruckLatitude
TruckLongitude
TruckIsOffTrack
RouteID

sensor.hemglass_truck har ett tillstånd och följande attribut:
Latitude
Longitude
TruckIsActiveToday
TruckLocationUpdated
TruckIsOffTrack
RouteID

När jag lägger till integratinen hemma (Lat 60,32 och Long 16,51) skapas bara sensor.hemglass_truck med nedanstående attribut trots att det finns ett stopp enligt hemglass sida och att bilen ska komma idag.
Latitude
Longitude
TruckIsActiveToday
TruckLocationUpdated
TruckIsOffTrack
RouteID

**Comment by popeen** [comment]
Tack för att du tog med koordinater så jag kan felsöka, jag ska försöka kika på det ikväll

**Comment by HAPSagan** [comment]
Toppen! Ingen panik, ta det när du får en lucka. Kollegan har testat och han får samma resultat med mina koordinater, medan hans fungerar där han bor.

**Comment by popeen** [comment]
Kika gärna om du ser något felmeddelande för Hemglass här
https://my.home-assistant.io/redirect/logs/?

Jag får båda när jag testar med Lat 60.32 och Long 16.51 nu men det är nog inte omöjligt att APIet ger lite annorlunda svar idag. Prova gärna om det fungerar för dig nu med. Jag får nog göra om lite hur den hanterar stopp tror jag.

**Comment by HAPSagan** [comment]
Jag måste be om ursäkt. I mitt experimenterande måste jag ha snurrat till det med koordinaterna när jag skrev detta issue. De koordinater som är aktuella och som bara ger det resultat jag skrev från början är: Lat: 60.61 Long: 16.77. Dessa ger i mitt försök bara en sensor. Testade med de koordinater du testat och dessa ger båda sensorerna. Alltså något mystiskt med mina.

**Comment by popeen** [comment]
Jajjemen, APIet rapporterade lite mysko på dina koordinater men nu så, om du uppdaterar till 24.04.1 så kommer det börja fungera även där.  Publicerade den precis så kan vara så att din HACS inte fattat att det kommit en ny version än, isf kan du tvinga den att hitta det genom att gå till HACS -> Hemglass , klicka upp menyn under prickarna uppe till höger och välj redownload
